---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/docker
  color: "3970E4"
- name: area/github
  color: "000000"
- name: area/go
  color: "844FBA"

# =================================================================================================
# Renovate Types
# =================================================================================================
- name: renovate/go
  color: "844FBA"
- name: renovate/container
  color: "3970E4"
- name: renovate/github-action
  color: "000000"

# =================================================================================================
# Semantic Types
# =================================================================================================
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"

# =================================================================================================
# Size Types
# =================================================================================================
- name: size/XS
  color: "0000ff"
- name: size/S
  color: "000ff0"
- name: size/M
  color: "00ff00"
- name: size/L
  color: "0ff000"
- name: size/XL
  color: "ff0000"
- name: size/XXL
  color: "ff00ff"

# =================================================================================================
# Issue Types
# =================================================================================================
- name: issue/bug
  color: "ff0000"
- name: issue/feature
  color: "00ff00"
- name: issue/chore
  color: "0000ff"
