---
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - a-multi-record.yaml
  - a-record.yaml
  - aaaa-multi-record.yaml
  - aaaa-record.yaml
  - cname-record.yaml
  - complex-record.yaml
  - mx-record.yaml
  - ns-record.yaml
  - srv-record.yaml
  - text-record.yaml
